freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  name: stable FreeBSD
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all
